services:
  - type: web
    name: zita-gadelha
    runtime: static
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /psicologa-online
        destination: /psicologa-online.html
